include:
    - project: 'ci-templates/common'
      file:
        - '/rules.yml'
        - '/version.yml'
      ref: stable/v1

before_script:

  # configuration for NPM proxy
  - printf "registry=http://rpm.svc/repository/npm-all/\n" > .npmrc  

  # получаем версию
  - !reference [.sc_common_build_version]
  #- git fetch --tags
  #- VER=$(git describe --match "[0-9]*" --abbrev=9 --tags HEAD --always)
  #- PACKAGE_VERSION=`echo $VER | sed -r 's/(.*)-.*/\1/' | sed -r 's/[-]+/./g' | sed -e 's/^v//'`

stages:
  - build
  - package

build_frontend:
  stage: build
  image: node:14.17.3
  extends: .sc_common_strict-build-rules
  variables:
    GIT_DEPTH: "200"
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    PACKAGE_NAME: "eir-web-frontend"
  script:
    - cd frontend/

    - yarn config set registry http://rpm.svc/repository/npm-all/
    # прописываем насильно версию в package.json
    # (необходимо сделать это прежде всего, иначе npm ругнётся что Git working directory is not clean)
    #- yarn version --no-git-tag-version --new-version $PACKAGE_VERSION
    - echo $SC_COMMON_SEMVER_BUILD_VERSION
    - yarn version --no-git-tag-version --new-version $SC_COMMON_SEMVER_BUILD_VERSION

    # дописываем файл .env переменными из конфигурации CI/CD
    - cp ../deploy/frontend.env .env

    - echo "@svyazcom-web-kit:registry=http://${CI_SERVER_HOST}/api/v4/packages/npm">.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/1206/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/1643/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc

    # ставим vue/cli и собираем проект
    - yarn --ignore-platform install
    #- yarn add @vue/cli
    - yarn build
    - cp .env dist/.env
    - cp -r ../deploy/configs dist/ci_configs #frontend/dist/ci_configs

  artifacts:
    name: "${CI_PROJECT_NAME}_frontend_`date +%Y%m%d-%H:%M:%S`"
    paths:
      - frontend/dist

build_backend:
  stage: build
  image: composer:2.0.8
  extends: .sc_common_strict-build-rules
  variables:
    GIT_DEPTH: "200"
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd backend/

    ## сразу запишем версию пакета в config
    - echo "<?php return ['package_version' => '$SC_COMMON_RPM_BUILD_VERSION'];" > config/ci.php
    
    - composer config gitlab-token.gitsrv.svyazcom.ru gitlab-ci-token $CI_JOB_TOKEN

    # устанавливаем зависимости composer без проверки php-расширений и оптимизируем работу
    - composer install --no-dev --optimize-autoloader --ignore-platform-reqs

    # Чтобы получить список необходимых расширений PHP, выполняем "composer check-platform-reqs".
    # Однако, этот функционал также проверит, какие из них не установлены; и вернёт exit code = 2
    # если установлены не все (а так оно в 99.9% и бывает во время интеграции). И разрушит CI/CD.
    # Поэтому вот такая обёртка в php, например. Кладем в файл список расширений для следующей стадии.
    - |
      php -r ' exec("composer check-platform-reqs", $lines, $result); print(implode("\n", $lines)); exit(0); ' \
        | awk '{ORS=","}{if (/^ext-/) print tolower($1)}' \
        | sed -r 's/ext/php/g' \
        > require_modules

    # перемещаем необходимое в каталог пакета
    - mkdir dist
    - |
      cp -r \
        app bootstrap config database public \
        resources routes storage tests vendor \
        artisan require_modules phpunit.xml \
        dist

    - cp ../deploy/backend.env dist/.env
    - cp composer.json dist/composer.json
    - cp composer.lock dist/composer.lock
    - rm -rf dist/vendor/svyazcom/api-core/.git
    - rm -f dist/vendor/svyazcom/api-core/.gitignore
    - rm -f dist/vendor/svyazcom/api-core/.gitlab-ci.yml
    - rm -f dist/vendor/svyazcom/api-core/README.md
  artifacts:
    name: "${CI_PROJECT_NAME}_backend_`date +%Y%m%d-%H:%M:%S`"
    paths:
      - backend/dist

# Этап создания и отправки пакета rpm в репозиторий
.package_template: &package_job_definition
  stage: package
  extends: .sc_common_strict-packaging-rules
  script:    
    - deploy/rpmbuild.sh common-eir-web $SC_COMMON_RPM_BUILD_VERSION eir
    - for pkg in rpmbuild/RPMS/*/*.rpm; do curl --upload-file $pkg "http://rpm.svc/download/index.php?filename=$(basename $pkg)&branch=master"; done
  artifacts:
    name: "${CI_PROJECT_NAME}_`date +%Y%m%d-%H:%M:%S`"
    paths:
      - rpmbuild/RPMS/*/*.rpm

.package:centos_6:
  <<: *package_job_definition
  image: registry.svc/svyazcom/development-env:6

.package:centos_7:
  <<: *package_job_definition
  image: registry.svc/svyazcom/development-env:7

package:centos_8:
  <<: *package_job_definition
  image: registry.svc/svyazcom/development-env:8

package:centos_9:
  <<: *package_job_definition
  image: registry.svc/svyazcom/development-env:9
